Bug exercises key
tmc-coach/tmc-coach pull request #152
Opened 2023-03-09 12:43 UTC by tikuisma

Fiksattu:
- key
- UI fiksaus "kurssiboxien" rivityksiin kurssit-sivulla

2023-03-11 08:52 UTC, tuukkalai reviewed
Pitäiskö noi `backend/migrations` ignorata, @murmurian ?

2023-03-11 16:42 UTC, murmurian commented
> Pitäiskö noi `backend/migrations` ignorata, @murmurian ?

Sanoisin et tässä kohtaa se vois olla ihan hyvä. Yleisesti kai olis hyvä käytäntö pitää ne repossa, mutta kun tällä hetkellä kaikilla taitaa kehitysympäristössä olla oma tietokanta viriteltynä lokaalisti, niin saattaa tulla jotain hässäkkää. Eli ehkä jos ei oo mitään muutoksia niihin malleihin, niin vois toistaiseksi ignorata. Tätä vois tarkemmin pohtia, kun tietokantaan tulee enemmän tauluja.

2023-03-11 23:53 UTC, tuukkalai requested changes
`Exercises.js` komponentin avaimen tulisi olla uniikki.

2023-03-11 23:53 UTC, tuukkalai commented on frontend/src/components/Exercises.js
> +      <div key={course_id}>
Nyt jos `exercises` muuttuja sisältää useamman tehtävän, tulee kaikkien niiden elementtien avaimeksi `course_id`.
Jos API:sta tulee aina yksi objekti arrayn sisällä, tai jos arraystä halutaan vain ensimmäinen objekti, voisi olla parempi renderöidä ainoastaan se (`<div key={exercises[0].course_id}>`), ilman `map()`:ia.

2023-03-13 09:44 UTC, tikuisma commented on frontend/src/components/Exercises.js
> +      <div key={course_id}>
Ahaa, oon ymmärtänyt ton toiminnon vähän hassusti.. Yritän korjailla!

2023-03-14 10:06 UTC, tuukkalai approved these changes
Toimii :+1:

2023-03-14 10:34 UTC, merged